name: CI - Nix Master board SDK

on: [push, pull_request]

jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: CI (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gepetto
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L
      - name: Debug Nix inputs
        if: "!cancelled()"
        run: nix show-derivation ./.
      - name: Check if there are changes
        uses: NathanielHill/fail-if-changes@v1.1.1
